---
- name: install stow
  become: true
  apt:
    name:
      - stow
    state: present


- name: "stow all configs" 
  dandyrow.linux.stow.stow:
    src: . 
    dest: "{{ ansible_env.HOME }}"
    package: [ kitty, lazygit, nvim, tmux, venv, wallpapers, zathura, bash, fonts]
    force: true
