---
# copying config
- name: install stow
  become: true
  apt:
    name:
      - stow

- name: "stow gui apps configs" 
  dandyrow.linux.stow.stow:
    src: . 
    dest: "{{ ansible_env.HOME }}"
    package: [ kitty, wallpapers, zathura, xmonad, gtk ]
    force: true

- name: installing xmonad tools and dependecies
  become: true 
  apt: 
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
      - haskell-stack
      - xmobar # the bar
      - dunst # notification manager
      - gdm3 # login manager

- name: install xmonad
  command: "stack install"
  args:
    chdir: "{{ ansible_user_dir }}/.config/xmonad"
    creates: "{{ ansible_user_dir }}/.local/bin/xmonad"

- name: install GUI apps from apt
  become: true
  apt:
    name:
      # add some configurability to gnome
      # - gnome-tweaks
      # - dconf-cli
      # - dconf-editor
      # gui applications i use
      - firefox-esr # main browser
      - chromium # backup browser for the sites that don't support firefox
      - calibre # ebook manager
      - zathura # pdf viewer
      - kitty # terminal emulator 
      - zeal # offline documentation
      - calibre # ebook manager
      # - virtualbox # virtual machines go brrr
      # - virtualbox-ext-pack #  virtualbox extension (do i really need them?)
      - flatpak # all my homies hate snaps
      # utilities
      - suckless-tools

- name: add the flathub flatpak remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install gui apps from flathub
  community.general.flatpak:
    name: 
      - com.discordapp.Discord # chatting app
      - com.spotify.Client # music
      - io.dbeaver.DBeaverCommunity # SQL server manger
      - com.sublimetext.three # i use this a my notepad (NVIM SUPERIORITY)

