---
# copying config
- name: install stow
  become: true
  apt:
    name:
      - stow

- name: "stow gui apps configs" 
  dandyrow.linux.stow.stow:
    src: . 
    dest: "{{ ansible_env.HOME }}"
    package: [ kitty, wallpapers, zathura, xmonad, gtk, autorandr ]
    force: true

- name: installing xmonad tools and dependecies
  become: true 
  apt: 
    name:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
      - haskell-stack
      - xmobar # the bar
      - dunst # notification manager
      - gdm3 # login manager
      - picom # compositor
      - feh # for the wallpaper
      - arandr # to manage displays
      - autorandr # to automatically switch configuration

- name: install xmonad
  command: "stack install"
  args:
    chdir: "{{ ansible_user_dir }}/.config/xmonad"
    creates: "{{ ansible_user_dir }}/.local/bin/xmonad"

- name: create xmonad.desktop for GDM
  become: true
  copy:
    dest: /usr/share/xsessions/xmonad.desktop
    content: |
      [Desktop Entry]
      Name=XMonad
      Comment=Lightweight tiling window manager
      Exec=/etc/X11/Xsession 
      Type=Application
      DesktopNames=XMonad

- name: register XMonad as an alternative for x-window-manager
  become: true
  alternatives:
    name: x-window-manager
    path: "{{ ansible_user_dir }}/.local/bin/xmonad"
    link: "/usr/bin/x-window-manager"
    priority: 100


- name: install GUI apps from apt
  become: true
  apt:
    name:
      # add some configurability to gnome
      # - gnome-tweaks
      # - dconf-cli
      # - dconf-editor
      - firefox-esr # main browser
      - chromium # backup browser for the sites that don't support firefox
      - calibre # ebook manager
      - zathura # pdf viewer
      - kitty # terminal emulator 
      - zeal # offline documentation
      - calibre # ebook manager
      - flameshot # screenshots
      - flatpak # all my homies hate snaps
      # utilities
      - suckless-tools
      - wezterm # another terminal emulator
      - pulsemixer # to control volume
      - brightnessctl # to control backlight
      - net-tools # network

- name: add the flathub flatpak remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: install gui apps from flathub
  community.general.flatpak:
    name: 
      - com.discordapp.Discord # chatting app
      - com.spotify.Client # music
      - io.dbeaver.DBeaverCommunity # SQL server manger
      - com.sublimetext.three # i use this a my notepad (NVIM SUPERIORITY)
      # - org.kicad.KiCad # I may need it sometimes in the future
      - md.obsidian.Obsidian # notes app

# TODO: it does not seem to work
- name: disable sublime updates
  become: true
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 www.sublimetext.com"
