require 'nvim-treesitter.configs'.setup {
	-- here you can find other languages https://github.com/nvim-treesitter/nvim-treesitter#supported-languages
	ensure_installed = {
		"c",
		"cpp",
		"vim",
		"vimdoc",
		"rust",
		"go",
		"query",
		"javascript",
		"css",
		"html",
		"bash",
		"lua",
		"cmake",
		"make",
		"csv",
		"dockerfile",
		"yaml",
		-- "haskell",
		"json",
		"json5",
		"markdown",
		"meson",
		"ninja",
		"python",
		"regex",
		"sql",
		"ssh_config",
	},
	sync_install = false,
	auto_install = false,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
}

require 'treesitter-context'.setup()
