- name: install prerequisites
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: add Docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add Docker APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: install Docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: ensure Docker is started and enabled
  become: true
  systemd:
    name: docker
    enabled: true
    state: started

- name: add user to the Docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

