---
# FIXME: lazygit is missing
- name: install dev dependencies from apt
  become: true
  apt:
    name:
      # building tools
      - x11-xkb-utils
      - build-essential
      - ninja-build 
      - gettext
      - cmake
      - unzip
      - curl 
      - gcc
      - g++
      - clang
      - pkg-config
      - libssl-dev
      - npm # requirement of mason.nvim
      - nodejs # requirement of mason.nvim
      # tools i actually use
      - fzf
      - bash-completion
      - tmux
      - git
      - htop
      - vagrant

- name: stow
  include_tasks: stow.yaml

- name: getting rusty!
  include_tasks: rust.yaml

- name: install neovim
  include_tasks: nvim.yaml

- name: go go go! 
  include_tasks: golang.yaml

- name: install docker
  include_tasks: docker.yaml

- name: virtualpilling
  include_tasks: virtualbox.yaml
