---
# FIXME: lazygit is missing
- name: install dev dependencies from apt
  become: true
  apt:
    name:
      # building tools
      - x11-xkb-utils
      - build-essential
      - ninja-build 
      - gettext
      - cmake
      - unzip
      - curl 
      - gcc
      - g++
      - clang
      - pkg-config
      - libssl-dev
      # tools i actually use
      - bash-completion
      - tmux
      - git
      - htop

- name: ensure conflicting packages are not installed
  become: true
  apt: 
    name:
      - neovim
      # maybe add rust ?

- name: download and install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"

- name: ensure rustup is updated
  shell: ./rustup update
  args:
    chdir: "{{ ansible_env.HOME }}/.cargo/bin/"
  register: rustup_update_result
  changed_when: "rustup_update_result.stdout.find('unchanged') == -1"

# necessary to have rust in the path
- name: resource .profile for the current session
  shell: source "{{ ansible_env.HOME }}/.profile"
  args:
    executable: /bin/bash
  changed_when: false

- name: install rust tools
  community.general.cargo:
    executable: "{{ ansible_env.HOME }}/.cargo/bin/cargo"
    name: 
      - ripgrep # better grep (dependency of telescope.nvim)
      - fd-find # better find (dependency of telescope.nvim)
      - exa # better ls
      - bat # better cat
      - bob-nvim # version manager for vim
      - starship # shell prompt
      - gitui # better lazygit
      - wiki-tui 
      - speedtest-rs
      # - zellij # better tmux (?)
    locked: true

- name: install neovim stable with bob
  command: ./bob use stable
  args:
    chdir: "{{ ansible_env.HOME }}/.cargo/bin/"
    creates: "{{ ansible_env.HOME }}/.local/share/bob/nvim-bin/nvim"
