#theme
include ./theme.conf

#layout
enabled_layouts tall:bias=62;full_size=1;mirrored=false
map ctrl+. layout_action bias 50 62 70
map ctrl+, layout_action bias 62

map ctrl+shift+t new_tab_with_cwd 
map ctrl+shift+enter new_window_with_cwd 

# go to specific tab
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4

# font
font_family "MonoLisa Nerd Font"
font_size 12
scrollback_lines 2000
disable_ligatures never

# don't annoy me please
enable_audio_bell no 
confirm_os_window_close 0

# looks
hide_window_decorations no
wayland_titlebar_color #1E1E2E
background_opacity 1
sync_to_monitor yes
# cursor_trail 1
# cursor_trail_decay 0.2 0.4

cursor_trail 3
cursor_trail_decay 0.2 0.3
cursor_trail_start_threshold 3

# my precious ctrl + backspace
map ctrl+backspace send_text all \x17
